// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Personregister.Infrastructure.Persistence.Context;

#nullable disable

namespace Personregister.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(Personregistercontext))]
    partial class PersonregistercontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Personregister.Domene.Dødsfall", b =>
                {
                    b.Property<int>("DødsfallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DødsfallId"), 1L, 1);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("dødsTid")
                        .HasColumnType("datetime2");

                    b.Property<string>("dødsårsak")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DødsfallId");

                    b.HasIndex("PersonId");

                    b.ToTable("Dødsfall");
                });

            modelBuilder.Entity("Personregister.Domene.Fødsel", b =>
                {
                    b.Property<int>("FødselId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FødselId"), 1L, 1);

                    b.Property<int?>("barnPersonId")
                        .HasColumnType("int");

                    b.Property<int?>("farPersonId")
                        .HasColumnType("int");

                    b.Property<DateTime>("fødselTid")
                        .HasColumnType("datetime2");

                    b.Property<int?>("morPersonId")
                        .HasColumnType("int");

                    b.HasKey("FødselId");

                    b.HasIndex("barnPersonId");

                    b.HasIndex("farPersonId");

                    b.HasIndex("morPersonId");

                    b.ToTable("Fødsler");
                });

            modelBuilder.Entity("Personregister.Domene.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"), 1L, 1);

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kallenavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Personnummer")
                        .HasColumnType("bigint");

                    b.HasKey("PersonId");

                    b.ToTable("Personer");
                });

            modelBuilder.Entity("Personregister.Domene.Dødsfall", b =>
                {
                    b.HasOne("Personregister.Domene.Person", "person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("person");
                });

            modelBuilder.Entity("Personregister.Domene.Fødsel", b =>
                {
                    b.HasOne("Personregister.Domene.Person", "barn")
                        .WithMany()
                        .HasForeignKey("barnPersonId");

                    b.HasOne("Personregister.Domene.Person", "far")
                        .WithMany()
                        .HasForeignKey("farPersonId");

                    b.HasOne("Personregister.Domene.Person", "mor")
                        .WithMany()
                        .HasForeignKey("morPersonId");

                    b.Navigation("barn");

                    b.Navigation("far");

                    b.Navigation("mor");
                });
#pragma warning restore 612, 618
        }
    }
}
