version: "3.7"
services:
  sql-server-db:
    container_name: sql1
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1401:1433"   
    environment:
      Name: "SqlLmrDw1"
      ACCEPT_EULA: "Y"
      MSSQL_COLLATION: "Danish_Norwegian_CI_AS" 
      SA_PASSWORD: "Password9!"
 
